package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventSkill generated by hbm2java
 */
public class EventSkill implements java.io.Serializable {

	private EventSkillId id;
	private Event event;
	private Skill skill;
	private byte required;

	public EventSkill() {
	}

	public EventSkill(EventSkillId id, Event event, Skill skill, byte required) {
		this.id = id;
		this.event = event;
		this.skill = skill;
		this.required = required;
	}

	public EventSkillId getId() {
		return this.id;
	}

	public void setId(EventSkillId id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	public byte getRequired() {
		return this.required;
	}

	public void setRequired(byte required) {
		this.required = required;
	}

}
