package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventVolunteer generated by hbm2java
 */
public class EventVolunteer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6092690213028029674L;
	private Integer eventVolunteerId;
	private Event event;
	private Volunteer volunteer;
	private Integer attendedHours;
	private Boolean approved;

	public EventVolunteer() {
	}

	public EventVolunteer(Event event, Volunteer volunteer) {
		this.event = event;
		this.volunteer = volunteer;
	}

	public EventVolunteer(Event event, Volunteer volunteer, Integer attendedHours, Boolean approved) {
		this.event = event;
		this.volunteer = volunteer;
		this.attendedHours = attendedHours;
		this.approved = approved;
	}

	public Integer getEventVolunteerId() {
		return this.eventVolunteerId;
	}

	public void setEventVolunteerId(Integer eventVolunteerId) {
		this.eventVolunteerId = eventVolunteerId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public Integer getAttendedHours() {
		return this.attendedHours;
	}

	public void setAttendedHours(Integer attendedHours) {
		this.attendedHours = attendedHours;
	}

	public Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(Boolean approved) {
		this.approved = approved;
	}

}
