package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventSkillId generated by hbm2java
 */
public class EventSkillId implements java.io.Serializable {

	private int skillId;
	private int eventId;

	public EventSkillId() {
	}

	public EventSkillId(int skillId, int eventId) {
		this.skillId = skillId;
		this.eventId = eventId;
	}

	public int getSkillId() {
		return this.skillId;
	}

	public void setSkillId(int skillId) {
		this.skillId = skillId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventSkillId))
			return false;
		EventSkillId castOther = (EventSkillId) other;

		return (this.getSkillId() == castOther.getSkillId()) && (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSkillId();
		result = 37 * result + this.getEventId();
		return result;
	}

}
