package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventVolunteer generated by hbm2java
 */
public class EventVolunteer implements java.io.Serializable {

	private EventVolunteerId id;
	private Event event;
	private Volunteer volunteer;
	private int attendedHours;
	private String approved;

	public EventVolunteer() {
	}

	public EventVolunteer(EventVolunteerId id, Event event, Volunteer volunteer, int attendedHours, String approved) {
		this.id = id;
		this.event = event;
		this.volunteer = volunteer;
		this.attendedHours = attendedHours;
		this.approved = approved;
	}

	public EventVolunteerId getId() {
		return this.id;
	}

	public void setId(EventVolunteerId id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public int getAttendedHours() {
		return this.attendedHours;
	}

	public void setAttendedHours(int attendedHours) {
		this.attendedHours = attendedHours;
	}

	public String getApproved() {
		return this.approved;
	}

	public void setApproved(String approved) {
		this.approved = approved;
	}

}
