package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3137927561212281037L;
	private Integer eventId;
	private OccurrencePattern occurrencePattern;
	private String eventName;
	private String description;
	private String location;
	private Date beginTime;
	private Date endTime;
	private Float hoursBonus;
	private Set<EventVolunteer> eventVolunteers = new HashSet<EventVolunteer>(0);
	private Set<Picture> pictures = new HashSet<Picture>(0);
	private Set<Interest> interests = new HashSet<Interest>(0);
	private Set<EventSkill> eventSkills = new HashSet<EventSkill>(0);

	public Event() {
	}

	public Event(String eventName, Date beginTime, Date endTime) {
		this.eventName = eventName;
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public Event(OccurrencePattern occurrencePattern, String eventName, String description, String location, Date beginTime, Date endTime, Float hoursBonus,
			Set<EventVolunteer> eventVolunteers, Set<Picture> pictures, Set<Interest> interests, Set<EventSkill> eventSkills) {
		this.occurrencePattern = occurrencePattern;
		this.eventName = eventName;
		this.description = description;
		this.location = location;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.hoursBonus = hoursBonus;
		this.eventVolunteers = eventVolunteers;
		this.pictures = pictures;
		this.interests = interests;
		this.eventSkills = eventSkills;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public OccurrencePattern getOccurrencePattern() {
		return this.occurrencePattern;
	}

	public void setOccurrencePattern(OccurrencePattern occurrencePattern) {
		this.occurrencePattern = occurrencePattern;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Float getHoursBonus() {
		return this.hoursBonus;
	}

	public void setHoursBonus(Float hoursBonus) {
		this.hoursBonus = hoursBonus;
	}

	public Set<EventVolunteer> getEventVolunteers() {
		return this.eventVolunteers;
	}

	public void setEventVolunteers(Set<EventVolunteer> eventVolunteers) {
		this.eventVolunteers = eventVolunteers;
	}

	public Set<Picture> getPictures() {
		return this.pictures;
	}

	public void setPictures(Set<Picture> pictures) {
		this.pictures = pictures;
	}

	public Set<Interest> getInterests() {
		return this.interests;
	}

	public void setInterests(Set<Interest> interests) {
		this.interests = interests;
	}

	public Set<EventSkill> getEventSkills() {
		return this.eventSkills;
	}

	public void setEventSkills(Set<EventSkill> eventSkills) {
		this.eventSkills = eventSkills;
	}

}
