package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * FacebookLogIn generated by hbm2java
 */
public class FacebookLogIn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8197062469592589159L;
	private Integer facebookLogInId;
	private Volunteer volunteer;
	private String token;

	public FacebookLogIn() {
	}

	public FacebookLogIn(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public FacebookLogIn(Volunteer volunteer, String token) {
		this.volunteer = volunteer;
		this.token = token;
	}

	public Integer getFacebookLogInId() {
		return this.facebookLogInId;
	}

	public void setFacebookLogInId(Integer facebookLogInId) {
		this.facebookLogInId = facebookLogInId;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
