package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * FacebookLogIn generated by hbm2java
 */
public class FacebookLogIn implements java.io.Serializable {

	private FacebookLogInId id;
	private Volunteer volunteer;
	private String token;

	public FacebookLogIn() {
	}

	public FacebookLogIn(FacebookLogInId id, Volunteer volunteer, String token) {
		this.id = id;
		this.volunteer = volunteer;
		this.token = token;
	}

	public FacebookLogInId getId() {
		return this.id;
	}

	public void setId(FacebookLogInId id) {
		this.id = id;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
