package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * GoogleLogIn generated by hbm2java
 */
public class GoogleLogIn implements java.io.Serializable {

	private GoogleLogInId id;
	private Volunteer volunteer;
	private String token;

	public GoogleLogIn() {
	}

	public GoogleLogIn(GoogleLogInId id, Volunteer volunteer, String token) {
		this.id = id;
		this.volunteer = volunteer;
		this.token = token;
	}

	public GoogleLogInId getId() {
		return this.id;
	}

	public void setId(GoogleLogInId id) {
		this.id = id;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
