package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer groupId;
	private String groupName;
	private String groupAdmin;
	private int hoursWorked;
	private float points;
	private float avgRatingOfVolunteers;
	private Set organizations = new HashSet(0);
	private Set groupMembers = new HashSet(0);
	private Set pictures = new HashSet(0);
	private Set groupMods = new HashSet(0);

	public Group() {
	}

	public Group(String groupName, String groupAdmin, int hoursWorked, float points, float avgRatingOfVolunteers) {
		this.groupName = groupName;
		this.groupAdmin = groupAdmin;
		this.hoursWorked = hoursWorked;
		this.points = points;
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
	}

	public Group(String groupName, String groupAdmin, int hoursWorked, float points, float avgRatingOfVolunteers, Set organizations, Set groupMembers,
			Set pictures, Set groupMods) {
		this.groupName = groupName;
		this.groupAdmin = groupAdmin;
		this.hoursWorked = hoursWorked;
		this.points = points;
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
		this.organizations = organizations;
		this.groupMembers = groupMembers;
		this.pictures = pictures;
		this.groupMods = groupMods;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupAdmin() {
		return this.groupAdmin;
	}

	public void setGroupAdmin(String groupAdmin) {
		this.groupAdmin = groupAdmin;
	}

	public int getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(int hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	public float getPoints() {
		return this.points;
	}

	public void setPoints(float points) {
		this.points = points;
	}

	public float getAvgRatingOfVolunteers() {
		return this.avgRatingOfVolunteers;
	}

	public void setAvgRatingOfVolunteers(float avgRatingOfVolunteers) {
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
	}

	public Set getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set organizations) {
		this.organizations = organizations;
	}

	public Set getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set groupMembers) {
		this.groupMembers = groupMembers;
	}

	public Set getPictures() {
		return this.pictures;
	}

	public void setPictures(Set pictures) {
		this.pictures = pictures;
	}

	public Set getGroupMods() {
		return this.groupMods;
	}

	public void setGroupMods(Set groupMods) {
		this.groupMods = groupMods;
	}

}
