package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4197778325590886129L;
	private Integer groupId;
	private String groupName;
	private Integer hoursWorked;
	private Float points;
	private Float avgRatingOfVolunteers;
	private Date creationDate;
	private Set<Organization> organizations = new HashSet<Organization>(0);
	private Set<Picture> pictures = new HashSet<Picture>(0);
	private Set<GroupMember> groupMembers = new HashSet<GroupMember>(0);

	public Group() {
	}

	public Group(String groupName) {
		this.groupName = groupName;
	}

	public Group(String groupName, Integer hoursWorked, Float points, Float avgRatingOfVolunteers, Date creationDate, Set<Organization> organizations,
			Set<Picture> pictures, Set<GroupMember> groupMembers) {
		this.groupName = groupName;
		this.hoursWorked = hoursWorked;
		this.points = points;
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
		this.creationDate = creationDate;
		this.organizations = organizations;
		this.pictures = pictures;
		this.groupMembers = groupMembers;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Integer getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(Integer hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	public Float getPoints() {
		return this.points;
	}

	public void setPoints(Float points) {
		this.points = points;
	}

	public Float getAvgRatingOfVolunteers() {
		return this.avgRatingOfVolunteers;
	}

	public void setAvgRatingOfVolunteers(Float avgRatingOfVolunteers) {
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Set<Organization> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}

	public Set<Picture> getPictures() {
		return this.pictures;
	}

	public void setPictures(Set<Picture> pictures) {
		this.pictures = pictures;
	}

	public Set<GroupMember> getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set<GroupMember> groupMembers) {
		this.groupMembers = groupMembers;
	}

}
