package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Interest generated by hbm2java
 */
public class Interest implements java.io.Serializable {

	private Integer interestId;
	private String name;
	private String description;
	private Set volunteerInterests = new HashSet(0);
	private Set events = new HashSet(0);

	public Interest() {
	}

	public Interest(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Interest(String name, String description, Set volunteerInterests, Set events) {
		this.name = name;
		this.description = description;
		this.volunteerInterests = volunteerInterests;
		this.events = events;
	}

	public Integer getInterestId() {
		return this.interestId;
	}

	public void setInterestId(Integer interestId) {
		this.interestId = interestId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getVolunteerInterests() {
		return this.volunteerInterests;
	}

	public void setVolunteerInterests(Set volunteerInterests) {
		this.volunteerInterests = volunteerInterests;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
