package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by hbm2java
 */
public class Notification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2658442898819124170L;
	private Integer notificationId;
	private String description;
	private String category;
	private String key;
	private String value;
	private Date creation;
	private Date dependenceDate;
	private Set<Volunteer> volunteers = new HashSet<Volunteer>(0);

	public Notification() {
	}

	public Notification(String description) {
		this.description = description;
	}

	public Notification(String description, String category, String key, String value, Date creation, Date dependenceDate, Set<Volunteer> volunteers) {
		this.description = description;
		this.category = category;
		this.key = key;
		this.value = value;
		this.creation = creation;
		this.dependenceDate = dependenceDate;
		this.volunteers = volunteers;
	}

	public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getDependenceDate() {
		return this.dependenceDate;
	}

	public void setDependenceDate(Date dependenceDate) {
		this.dependenceDate = dependenceDate;
	}

	public Set<Volunteer> getVolunteers() {
		return this.volunteers;
	}

	public void setVolunteers(Set<Volunteer> volunteers) {
		this.volunteers = volunteers;
	}

}
