package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrganizationFollower generated by hbm2java
 */
public class OrganizationFollower implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4453637148850039711L;
	private Integer orgFollowerId;
	private Organization organization;
	private Volunteer volunteer;
	private Boolean mod;
	private Boolean admin;

	public OrganizationFollower() {
	}

	public OrganizationFollower(Organization organization, Volunteer volunteer) {
		this.organization = organization;
		this.volunteer = volunteer;
	}

	public OrganizationFollower(Organization organization, Volunteer volunteer, Boolean mod, Boolean admin) {
		this.organization = organization;
		this.volunteer = volunteer;
		this.mod = mod;
		this.admin = admin;
	}

	public Integer getOrgFollowerId() {
		return this.orgFollowerId;
	}

	public void setOrgFollowerId(Integer orgFollowerId) {
		this.orgFollowerId = orgFollowerId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public Boolean getMod() {
		return this.mod;
	}

	public void setMod(Boolean mod) {
		this.mod = mod;
	}

	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

}
