package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrganizationFollower generated by hbm2java
 */
public class OrganizationFollower implements java.io.Serializable {

	private OrganizationFollowerId id;
	private Organization organization;
	private Volunteer volunteer;
	private int orgFollowerId;

	public OrganizationFollower() {
	}

	public OrganizationFollower(OrganizationFollowerId id, Organization organization, Volunteer volunteer, int orgFollowerId) {
		this.id = id;
		this.organization = organization;
		this.volunteer = volunteer;
		this.orgFollowerId = orgFollowerId;
	}

	public OrganizationFollowerId getId() {
		return this.id;
	}

	public void setId(OrganizationFollowerId id) {
		this.id = id;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public int getOrgFollowerId() {
		return this.orgFollowerId;
	}

	public void setOrgFollowerId(int orgFollowerId) {
		this.orgFollowerId = orgFollowerId;
	}

}
