package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * PictureEventId generated by hbm2java
 */
public class PictureEventId implements java.io.Serializable {

	private int pictureId;
	private int eventId;

	public PictureEventId() {
	}

	public PictureEventId(int pictureId, int eventId) {
		this.pictureId = pictureId;
		this.eventId = eventId;
	}

	public int getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(int pictureId) {
		this.pictureId = pictureId;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PictureEventId))
			return false;
		PictureEventId castOther = (PictureEventId) other;

		return (this.getPictureId() == castOther.getPictureId()) && (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPictureId();
		result = 37 * result + this.getEventId();
		return result;
	}

}
