package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Picture generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	private Integer pictureId;
	private String pictureLink;
	private Date uploadedOn;
	private String albumName;
	private String description;
	private Set groups = new HashSet(0);
	private Set volunteers = new HashSet(0);
	private Set organizations = new HashSet(0);

	public Picture() {
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName, String description, Set groups, Set volunteers, Set organizations) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
		this.description = description;
		this.groups = groups;
		this.volunteers = volunteers;
		this.organizations = organizations;
	}

	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	public String getPictureLink() {
		return this.pictureLink;
	}

	public void setPictureLink(String pictureLink) {
		this.pictureLink = pictureLink;
	}

	public Date getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(Date uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getGroups() {
		return this.groups;
	}

	public void setGroups(Set groups) {
		this.groups = groups;
	}

	public Set getVolunteers() {
		return this.volunteers;
	}

	public void setVolunteers(Set volunteers) {
		this.volunteers = volunteers;
	}

	public Set getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set organizations) {
		this.organizations = organizations;
	}

}
