package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * PictureEvent generated by hbm2java
 */
public class PictureEvent implements java.io.Serializable {

	private PictureEventId id;

	public PictureEvent() {
	}

	public PictureEvent(PictureEventId id) {
		this.id = id;
	}

	public PictureEventId getId() {
		return this.id;
	}

	public void setId(PictureEventId id) {
		this.id = id;
	}

}
