package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Skill generated by hbm2java
 */
public class Skill implements java.io.Serializable {

	private Integer skillId;
	private String skillName;
	private String description;
	private Set eventSkills = new HashSet(0);
	private Set volunteerSkills = new HashSet(0);

	public Skill() {
	}

	public Skill(String skillName) {
		this.skillName = skillName;
	}

	public Skill(String skillName, String description, Set eventSkills, Set volunteerSkills) {
		this.skillName = skillName;
		this.description = description;
		this.eventSkills = eventSkills;
		this.volunteerSkills = volunteerSkills;
	}

	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getEventSkills() {
		return this.eventSkills;
	}

	public void setEventSkills(Set eventSkills) {
		this.eventSkills = eventSkills;
	}

	public Set getVolunteerSkills() {
		return this.volunteerSkills;
	}

	public void setVolunteerSkills(Set volunteerSkills) {
		this.volunteerSkills = volunteerSkills;
	}

}
