package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Skill generated by hbm2java
 */
public class Skill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1509098224903651848L;
	private Integer skillId;
	private String skillName;
	private String description;
	private Set<VolunteerSkill> volunteerSkills = new HashSet<VolunteerSkill>(0);
	private Set<EventSkill> eventSkills = new HashSet<EventSkill>(0);

	public Skill() {
	}

	public Skill(String skillName) {
		this.skillName = skillName;
	}

	public Skill(String skillName, String description, Set<VolunteerSkill> volunteerSkills, Set<EventSkill> eventSkills) {
		this.skillName = skillName;
		this.description = description;
		this.volunteerSkills = volunteerSkills;
		this.eventSkills = eventSkills;
	}

	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<VolunteerSkill> getVolunteerSkills() {
		return this.volunteerSkills;
	}

	public void setVolunteerSkills(Set<VolunteerSkill> volunteerSkills) {
		this.volunteerSkills = volunteerSkills;
	}

	public Set<EventSkill> getEventSkills() {
		return this.eventSkills;
	}

	public void setEventSkills(Set<EventSkill> eventSkills) {
		this.eventSkills = eventSkills;
	}

}
