package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * SocialLinks generated by hbm2java
 */
public class SocialLinks implements java.io.Serializable {

	private Integer socialId;
	private Volunteer volunteer;
	private String link;

	public SocialLinks() {
	}

	public SocialLinks(Volunteer volunteer, String link) {
		this.volunteer = volunteer;
		this.link = link;
	}

	public Integer getSocialId() {
		return this.socialId;
	}

	public void setSocialId(Integer socialId) {
		this.socialId = socialId;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
