package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * VolunteerInterest generated by hbm2java
 */
public class VolunteerInterest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2148548096891782600L;
	private Integer volunteerInterestId;
	private Interest interest;
	private Volunteer volunteer;
	private Boolean disinterest;

	public VolunteerInterest() {
	}

	public VolunteerInterest(Interest interest, Volunteer volunteer) {
		this.interest = interest;
		this.volunteer = volunteer;
	}

	public VolunteerInterest(Interest interest, Volunteer volunteer, Boolean disinterest) {
		this.interest = interest;
		this.volunteer = volunteer;
		this.disinterest = disinterest;
	}

	public Integer getVolunteerInterestId() {
		return this.volunteerInterestId;
	}

	public void setVolunteerInterestId(Integer volunteerInterestId) {
		this.volunteerInterestId = volunteerInterestId;
	}

	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public Boolean getDisinterest() {
		return this.disinterest;
	}

	public void setDisinterest(Boolean disinterest) {
		this.disinterest = disinterest;
	}

}
