package org.CommunityService.EntitiesUnmapped;

// Generated Feb 5, 2014 10:51:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * VolunteerSkill generated by hbm2java
 */
public class VolunteerSkill implements java.io.Serializable {

	private VolunteerSkillId id;
	private Skill skill;
	private Volunteer volunteer;
	private byte certified;
	private String certifiedFrom;

	public VolunteerSkill() {
	}

	public VolunteerSkill(VolunteerSkillId id, Skill skill, Volunteer volunteer, byte certified) {
		this.id = id;
		this.skill = skill;
		this.volunteer = volunteer;
		this.certified = certified;
	}

	public VolunteerSkill(VolunteerSkillId id, Skill skill, Volunteer volunteer, byte certified, String certifiedFrom) {
		this.id = id;
		this.skill = skill;
		this.volunteer = volunteer;
		this.certified = certified;
		this.certifiedFrom = certifiedFrom;
	}

	public VolunteerSkillId getId() {
		return this.id;
	}

	public void setId(VolunteerSkillId id) {
		this.id = id;
	}

	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public byte getCertified() {
		return this.certified;
	}

	public void setCertified(byte certified) {
		this.certified = certified;
	}

	public String getCertifiedFrom() {
		return this.certifiedFrom;
	}

	public void setCertifiedFrom(String certifiedFrom) {
		this.certifiedFrom = certifiedFrom;
	}

}
