package org.CommunityService.EntitiesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * VolunteerSkill generated by hbm2java
 */
public class VolunteerSkill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4372986878961579761L;
	private Integer volunteerSkillId;
	private Skill skill;
	private Volunteer volunteer;
	private Boolean certified;
	private String certifiedFrom;

	public VolunteerSkill() {
	}

	public VolunteerSkill(Skill skill, Volunteer volunteer) {
		this.skill = skill;
		this.volunteer = volunteer;
	}

	public VolunteerSkill(Skill skill, Volunteer volunteer, Boolean certified, String certifiedFrom) {
		this.skill = skill;
		this.volunteer = volunteer;
		this.certified = certified;
		this.certifiedFrom = certifiedFrom;
	}

	public Integer getVolunteerSkillId() {
		return this.volunteerSkillId;
	}

	public void setVolunteerSkillId(Integer volunteerSkillId) {
		this.volunteerSkillId = volunteerSkillId;
	}

	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public Boolean getCertified() {
		return this.certified;
	}

	public void setCertified(Boolean certified) {
		this.certified = certified;
	}

	public String getCertifiedFrom() {
		return this.certifiedFrom;
	}

	public void setCertifiedFrom(String certifiedFrom) {
		this.certifiedFrom = certifiedFrom;
	}

}
