package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventSkill generated by hbm2java
 */
public class EventSkill implements java.io.Serializable {

	private Integer eventSkillId;
	private Event event;
	private Skill skill;
	private byte required;

	public EventSkill() {
	}

	public EventSkill(Event event, Skill skill, byte required) {
		this.event = event;
		this.skill = skill;
		this.required = required;
	}

	public Integer getEventSkillId() {
		return this.eventSkillId;
	}

	public void setEventSkillId(Integer eventSkillId) {
		this.eventSkillId = eventSkillId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	public byte getRequired() {
		return this.required;
	}

	public void setRequired(byte required) {
		this.required = required;
	}

}
