package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventInterests generated by hbm2java
 */
public class EventInterests implements java.io.Serializable {

	private Integer eventInterestsId;
	private Event event;
	private Interest interest;

	public EventInterests() {
	}

	public EventInterests(Event event, Interest interest) {
		this.event = event;
		this.interest = interest;
	}

	public Integer getEventInterestsId() {
		return this.eventInterestsId;
	}

	public void setEventInterestsId(Integer eventInterestsId) {
		this.eventInterestsId = eventInterestsId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

}
