package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventVolunteer generated by hbm2java
 */
public class EventVolunteer implements java.io.Serializable {

	private int eventVolunteerId;
	private Event event;
	private Volunteer volunteer;
	private int attendedHours;

	public EventVolunteer() {
	}

	public EventVolunteer(int eventVolunteerId, Event event,
			Volunteer volunteer, int attendedHours) {
		this.eventVolunteerId = eventVolunteerId;
		this.event = event;
		this.volunteer = volunteer;
		this.attendedHours = attendedHours;
	}

	public int getEventVolunteerId() {
		return this.eventVolunteerId;
	}

	public void setEventVolunteerId(int eventVolunteerId) {
		this.eventVolunteerId = eventVolunteerId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public int getAttendedHours() {
		return this.attendedHours;
	}

	public void setAttendedHours(int attendedHours) {
		this.attendedHours = attendedHours;
	}

}
