package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer groupId;
	private String groupName;
	private String groupAdmin;
	private int hoursWorked;
	private float points;
	private float avgRatingOfVolunteers;
	private Set orgGroups = new HashSet(0);
	private Set groupMembers = new HashSet(0);
	private Set pictureGroups = new HashSet(0);
	private Set groupMods = new HashSet(0);

	public Group() {
	}

	public Group(String groupName, String groupAdmin, int hoursWorked,
			float points, float avgRatingOfVolunteers) {
		this.groupName = groupName;
		this.groupAdmin = groupAdmin;
		this.hoursWorked = hoursWorked;
		this.points = points;
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
	}

	public Group(String groupName, String groupAdmin, int hoursWorked,
			float points, float avgRatingOfVolunteers, Set orgGroups,
			Set groupMembers, Set pictureGroups, Set groupMods) {
		this.groupName = groupName;
		this.groupAdmin = groupAdmin;
		this.hoursWorked = hoursWorked;
		this.points = points;
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
		this.orgGroups = orgGroups;
		this.groupMembers = groupMembers;
		this.pictureGroups = pictureGroups;
		this.groupMods = groupMods;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getGroupAdmin() {
		return this.groupAdmin;
	}

	public void setGroupAdmin(String groupAdmin) {
		this.groupAdmin = groupAdmin;
	}

	public int getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(int hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	public float getPoints() {
		return this.points;
	}

	public void setPoints(float points) {
		this.points = points;
	}

	public float getAvgRatingOfVolunteers() {
		return this.avgRatingOfVolunteers;
	}

	public void setAvgRatingOfVolunteers(float avgRatingOfVolunteers) {
		this.avgRatingOfVolunteers = avgRatingOfVolunteers;
	}

	public Set getOrgGroups() {
		return this.orgGroups;
	}

	public void setOrgGroups(Set orgGroups) {
		this.orgGroups = orgGroups;
	}

	public Set getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set groupMembers) {
		this.groupMembers = groupMembers;
	}

	public Set getPictureGroups() {
		return this.pictureGroups;
	}

	public void setPictureGroups(Set pictureGroups) {
		this.pictureGroups = pictureGroups;
	}

	public Set getGroupMods() {
		return this.groupMods;
	}

	public void setGroupMods(Set groupMods) {
		this.groupMods = groupMods;
	}

}
