package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GroupMod generated by hbm2java
 */
public class GroupMod implements java.io.Serializable {

	private Integer groupModId;
	private Group group;
	private Volunteer volunteer;
	private Date modSince;

	public GroupMod() {
	}

	public GroupMod(Group group, Volunteer volunteer, Date modSince) {
		this.group = group;
		this.volunteer = volunteer;
		this.modSince = modSince;
	}

	public Integer getGroupModId() {
		return this.groupModId;
	}

	public void setGroupModId(Integer groupModId) {
		this.groupModId = groupModId;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public Date getModSince() {
		return this.modSince;
	}

	public void setModSince(Date modSince) {
		this.modSince = modSince;
	}

}
