package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization implements java.io.Serializable {

    private Integer orgId;
    private String orgName;
    private String address;
    private String phoneNumber;
    private String emailAddress;
    private String description;
    private Date createdOn;
    private Set orgGroups = new HashSet(0);
    private Set orgFollowers = new HashSet(0);
    private Set pictureOrgs = new HashSet(0);
    private Set orgMods = new HashSet(0);

    public Organization() {
    }

    public Organization(String orgName, String address, String phoneNumber, String emailAddress) {
	this.orgName = orgName;
	this.address = address;
	this.phoneNumber = phoneNumber;
	this.emailAddress = emailAddress;
    }

    public Organization(String orgName, String address, String phoneNumber, String emailAddress, String description, Date createdOn, Set orgGroups,
	    Set orgFollowers, Set pictureOrgs, Set orgMods) {
	this.orgName = orgName;
	this.address = address;
	this.phoneNumber = phoneNumber;
	this.emailAddress = emailAddress;
	this.description = description;
	this.createdOn = createdOn;
	this.orgGroups = orgGroups;
	this.orgFollowers = orgFollowers;
	this.pictureOrgs = pictureOrgs;
	this.orgMods = orgMods;
    }

    public Integer getOrgId() {
	return this.orgId;
    }

    public void setOrgId(Integer orgId) {
	this.orgId = orgId;
    }

    public String getOrgName() {
	return this.orgName;
    }

    public void setOrgName(String orgName) {
	this.orgName = orgName;
    }

    public String getAddress() {
	return this.address;
    }

    public void setAddress(String address) {
	this.address = address;
    }

    public String getPhoneNumber() {
	return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
	this.phoneNumber = phoneNumber;
    }

    public String getEmailAddress() {
	return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
	this.emailAddress = emailAddress;
    }

    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    public Date getCreatedOn() {
	return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
	this.createdOn = createdOn;
    }

    public Set getOrgGroups() {
	return this.orgGroups;
    }

    public void setOrgGroups(Set orgGroups) {
	this.orgGroups = orgGroups;
    }

    public Set getOrgFollowers() {
	return this.orgFollowers;
    }

    public void setOrgFollowers(Set orgFollowers) {
	this.orgFollowers = orgFollowers;
    }

    public Set getPictureOrgs() {
	return this.pictureOrgs;
    }

    public void setPictureOrgs(Set pictureOrgs) {
	this.pictureOrgs = pictureOrgs;
    }

    public Set getOrgMods() {
	return this.orgMods;
    }

    public void setOrgMods(Set orgMods) {
	this.orgMods = orgMods;
    }

}
