package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrgFollower generated by hbm2java
 */
public class OrgFollower implements java.io.Serializable {

	private Integer orgFollowerId;
	private Organization organization;
	private Volunteer volunteer;

	public OrgFollower() {
	}

	public OrgFollower(Organization organization, Volunteer volunteer) {
		this.organization = organization;
		this.volunteer = volunteer;
	}

	public Integer getOrgFollowerId() {
		return this.orgFollowerId;
	}

	public void setOrgFollowerId(Integer orgFollowerId) {
		this.orgFollowerId = orgFollowerId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

}
