package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrgGroup generated by hbm2java
 */
public class OrgGroup implements java.io.Serializable {

	private int orgGroupId;
	private Organization organization;
	private Group group;

	public OrgGroup() {
	}

	public OrgGroup(int orgGroupId, Organization organization, Group group) {
		this.orgGroupId = orgGroupId;
		this.organization = organization;
		this.group = group;
	}

	public int getOrgGroupId() {
		return this.orgGroupId;
	}

	public void setOrgGroupId(int orgGroupId) {
		this.orgGroupId = orgGroupId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

}
