package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrgMod generated by hbm2java
 */
public class OrgMod implements java.io.Serializable {

	private int orgModId;
	private Organization organization;
	private Volunteer volunteer;

	public OrgMod() {
	}

	public OrgMod(int orgModId, Organization organization, Volunteer volunteer) {
		this.orgModId = orgModId;
		this.organization = organization;
		this.volunteer = volunteer;
	}

	public int getOrgModId() {
		return this.orgModId;
	}

	public void setOrgModId(int orgModId) {
		this.orgModId = orgModId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

}
