package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * PictureGroup generated by hbm2java
 */
public class PictureGroup implements java.io.Serializable {

	private Integer pictureGroupId;
	private Group group;
	private Picture picture;

	public PictureGroup() {
	}

	public PictureGroup(Group group, Picture picture) {
		this.group = group;
		this.picture = picture;
	}

	public Integer getPictureGroupId() {
		return this.pictureGroupId;
	}

	public void setPictureGroupId(Integer pictureGroupId) {
		this.pictureGroupId = pictureGroupId;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

}
