package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * PictureEvent generated by hbm2java
 */
public class PictureEvent implements java.io.Serializable {

	private int pictureEventId;
	private Event event;
	private Picture picture;

	public PictureEvent() {
	}

	public PictureEvent(int pictureEventId) {
		this.pictureEventId = pictureEventId;
	}

	public PictureEvent(int pictureEventId, Event event, Picture picture) {
		this.pictureEventId = pictureEventId;
		this.event = event;
		this.picture = picture;
	}

	public int getPictureEventId() {
		return this.pictureEventId;
	}

	public void setPictureEventId(int pictureEventId) {
		this.pictureEventId = pictureEventId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

}
