package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * PictureOrg generated by hbm2java
 */
public class PictureOrg implements java.io.Serializable {

	private int pictureOrgId;
	private Organization organization;
	private Picture picture;

	public PictureOrg() {
	}

	public PictureOrg(int pictureOrgId, Organization organization,
			Picture picture) {
		this.pictureOrgId = pictureOrgId;
		this.organization = organization;
		this.picture = picture;
	}

	public int getPictureOrgId() {
		return this.pictureOrgId;
	}

	public void setPictureOrgId(int pictureOrgId) {
		this.pictureOrgId = pictureOrgId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

}
