package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * PictureVolunteer generated by hbm2java
 */
public class PictureVolunteer implements java.io.Serializable {

	private int pictureVolunteerId;
	private Volunteer volunteer;
	private Picture picture;

	public PictureVolunteer() {
	}

	public PictureVolunteer(int pictureVolunteerId, Volunteer volunteer,
			Picture picture) {
		this.pictureVolunteerId = pictureVolunteerId;
		this.volunteer = volunteer;
		this.picture = picture;
	}

	public int getPictureVolunteerId() {
		return this.pictureVolunteerId;
	}

	public void setPictureVolunteerId(int pictureVolunteerId) {
		this.pictureVolunteerId = pictureVolunteerId;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

}
