package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Picture generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	private Integer pictureId;
	private String pictureLink;
	private Date uploadedOn;
	private String albumName;
	private String description;
	private Set pictureEvents = new HashSet(0);
	private Set pictureGroups = new HashSet(0);
	private Set pictureVolunteers = new HashSet(0);
	private Set pictureOrgs = new HashSet(0);

	public Picture() {
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName,
			String description, Set pictureEvents, Set pictureGroups,
			Set pictureVolunteers, Set pictureOrgs) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
		this.description = description;
		this.pictureEvents = pictureEvents;
		this.pictureGroups = pictureGroups;
		this.pictureVolunteers = pictureVolunteers;
		this.pictureOrgs = pictureOrgs;
	}

	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	public String getPictureLink() {
		return this.pictureLink;
	}

	public void setPictureLink(String pictureLink) {
		this.pictureLink = pictureLink;
	}

	public Date getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(Date uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPictureEvents() {
		return this.pictureEvents;
	}

	public void setPictureEvents(Set pictureEvents) {
		this.pictureEvents = pictureEvents;
	}

	public Set getPictureGroups() {
		return this.pictureGroups;
	}

	public void setPictureGroups(Set pictureGroups) {
		this.pictureGroups = pictureGroups;
	}

	public Set getPictureVolunteers() {
		return this.pictureVolunteers;
	}

	public void setPictureVolunteers(Set pictureVolunteers) {
		this.pictureVolunteers = pictureVolunteers;
	}

	public Set getPictureOrgs() {
		return this.pictureOrgs;
	}

	public void setPictureOrgs(Set pictureOrgs) {
		this.pictureOrgs = pictureOrgs;
	}

}
