package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * VolunteerDevice generated by hbm2java
 */
public class VolunteerDevice implements java.io.Serializable {

	private int volunteerDeviceId;
	private Volunteer volunteer;
	private String deviceId;
	private String deviceTokenInternal;

	public VolunteerDevice() {
	}

	public VolunteerDevice(int volunteerDeviceId, Volunteer volunteer,
			String deviceTokenInternal) {
		this.volunteerDeviceId = volunteerDeviceId;
		this.volunteer = volunteer;
		this.deviceTokenInternal = deviceTokenInternal;
	}

	public VolunteerDevice(int volunteerDeviceId, Volunteer volunteer,
			String deviceId, String deviceTokenInternal) {
		this.volunteerDeviceId = volunteerDeviceId;
		this.volunteer = volunteer;
		this.deviceId = deviceId;
		this.deviceTokenInternal = deviceTokenInternal;
	}

	public int getVolunteerDeviceId() {
		return this.volunteerDeviceId;
	}

	public void setVolunteerDeviceId(int volunteerDeviceId) {
		this.volunteerDeviceId = volunteerDeviceId;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getDeviceTokenInternal() {
		return this.deviceTokenInternal;
	}

	public void setDeviceTokenInternal(String deviceTokenInternal) {
		this.deviceTokenInternal = deviceTokenInternal;
	}

}
