package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Volunteer generated by hbm2java
 */
public class Volunteer implements java.io.Serializable {

	private Integer volunteerId;
	private String volunteerName;
	private String volunteerPassword;
	private int phoneNumber;
	private String emailAddress;
	private Date lastLoginDate;
	private float points;
	private int hoursWorked;
	private Float avgRating;
	private Date creationDate;
	private Date activationDate;
	private String adminOrg;
	private Set facebookLogIns = new HashSet(0);
	private Set eventVolunteers = new HashSet(0);
	private Set pictureVolunteers = new HashSet(0);
	private Set volunteerInterests = new HashSet(0);
	private Set orgMods = new HashSet(0);
	private Set groupMods = new HashSet(0);
	private Set orgFollowers = new HashSet(0);
	private Set googleLogIns = new HashSet(0);
	private Set groupMembers = new HashSet(0);
	private Set volunteerSkills = new HashSet(0);
	private Set volunteerDevices = new HashSet(0);

	public Volunteer() {
	}

	public Volunteer(String volunteerName, String volunteerPassword,
			int phoneNumber, String emailAddress, Date lastLoginDate,
			float points, int hoursWorked, Date creationDate) {
		this.volunteerName = volunteerName;
		this.volunteerPassword = volunteerPassword;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.lastLoginDate = lastLoginDate;
		this.points = points;
		this.hoursWorked = hoursWorked;
		this.creationDate = creationDate;
	}

	public Volunteer(String volunteerName, String volunteerPassword,
			int phoneNumber, String emailAddress, Date lastLoginDate,
			float points, int hoursWorked, Float avgRating, Date creationDate,
			Date activationDate, String adminOrg, Set facebookLogIns,
			Set eventVolunteers, Set pictureVolunteers, Set volunteerInterests,
			Set orgMods, Set groupMods, Set orgFollowers, Set googleLogIns,
			Set groupMembers, Set volunteerSkills, Set volunteerDevices) {
		this.volunteerName = volunteerName;
		this.volunteerPassword = volunteerPassword;
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.lastLoginDate = lastLoginDate;
		this.points = points;
		this.hoursWorked = hoursWorked;
		this.avgRating = avgRating;
		this.creationDate = creationDate;
		this.activationDate = activationDate;
		this.adminOrg = adminOrg;
		this.facebookLogIns = facebookLogIns;
		this.eventVolunteers = eventVolunteers;
		this.pictureVolunteers = pictureVolunteers;
		this.volunteerInterests = volunteerInterests;
		this.orgMods = orgMods;
		this.groupMods = groupMods;
		this.orgFollowers = orgFollowers;
		this.googleLogIns = googleLogIns;
		this.groupMembers = groupMembers;
		this.volunteerSkills = volunteerSkills;
		this.volunteerDevices = volunteerDevices;
	}

	public Integer getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(Integer volunteerId) {
		this.volunteerId = volunteerId;
	}

	public String getVolunteerName() {
		return this.volunteerName;
	}

	public void setVolunteerName(String volunteerName) {
		this.volunteerName = volunteerName;
	}

	public String getVolunteerPassword() {
		return this.volunteerPassword;
	}

	public void setVolunteerPassword(String volunteerPassword) {
		this.volunteerPassword = volunteerPassword;
	}

	public int getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(int phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public float getPoints() {
		return this.points;
	}

	public void setPoints(float points) {
		this.points = points;
	}

	public int getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(int hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	public Float getAvgRating() {
		return this.avgRating;
	}

	public void setAvgRating(Float avgRating) {
		this.avgRating = avgRating;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	public String getAdminOrg() {
		return this.adminOrg;
	}

	public void setAdminOrg(String adminOrg) {
		this.adminOrg = adminOrg;
	}

	public Set getFacebookLogIns() {
		return this.facebookLogIns;
	}

	public void setFacebookLogIns(Set facebookLogIns) {
		this.facebookLogIns = facebookLogIns;
	}

	public Set getEventVolunteers() {
		return this.eventVolunteers;
	}

	public void setEventVolunteers(Set eventVolunteers) {
		this.eventVolunteers = eventVolunteers;
	}

	public Set getPictureVolunteers() {
		return this.pictureVolunteers;
	}

	public void setPictureVolunteers(Set pictureVolunteers) {
		this.pictureVolunteers = pictureVolunteers;
	}

	public Set getVolunteerInterests() {
		return this.volunteerInterests;
	}

	public void setVolunteerInterests(Set volunteerInterests) {
		this.volunteerInterests = volunteerInterests;
	}

	public Set getOrgMods() {
		return this.orgMods;
	}

	public void setOrgMods(Set orgMods) {
		this.orgMods = orgMods;
	}

	public Set getGroupMods() {
		return this.groupMods;
	}

	public void setGroupMods(Set groupMods) {
		this.groupMods = groupMods;
	}

	public Set getOrgFollowers() {
		return this.orgFollowers;
	}

	public void setOrgFollowers(Set orgFollowers) {
		this.orgFollowers = orgFollowers;
	}

	public Set getGoogleLogIns() {
		return this.googleLogIns;
	}

	public void setGoogleLogIns(Set googleLogIns) {
		this.googleLogIns = googleLogIns;
	}

	public Set getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set groupMembers) {
		this.groupMembers = groupMembers;
	}

	public Set getVolunteerSkills() {
		return this.volunteerSkills;
	}

	public void setVolunteerSkills(Set volunteerSkills) {
		this.volunteerSkills = volunteerSkills;
	}

	public Set getVolunteerDevices() {
		return this.volunteerDevices;
	}

	public void setVolunteerDevices(Set volunteerDevices) {
		this.volunteerDevices = volunteerDevices;
	}

}
