package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * VolunteerSkill generated by hbm2java
 */
public class VolunteerSkill implements java.io.Serializable {

	private Integer volunteerSkillId;
	private Skill skill;
	private Volunteer volunteer;
	private byte certified;
	private String certifiedFrom;

	public VolunteerSkill() {
	}

	public VolunteerSkill(Skill skill, Volunteer volunteer, byte certified) {
		this.skill = skill;
		this.volunteer = volunteer;
		this.certified = certified;
	}

	public VolunteerSkill(Skill skill, Volunteer volunteer, byte certified,
			String certifiedFrom) {
		this.skill = skill;
		this.volunteer = volunteer;
		this.certified = certified;
		this.certifiedFrom = certifiedFrom;
	}

	public Integer getVolunteerSkillId() {
		return this.volunteerSkillId;
	}

	public void setVolunteerSkillId(Integer volunteerSkillId) {
		this.volunteerSkillId = volunteerSkillId;
	}

	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public byte getCertified() {
		return this.certified;
	}

	public void setCertified(byte certified) {
		this.certified = certified;
	}

	public String getCertifiedFrom() {
		return this.certifiedFrom;
	}

	public void setCertifiedFrom(String certifiedFrom) {
		this.certifiedFrom = certifiedFrom;
	}

}
