package org.CommunityService.Entities.DEPRECATED;

// Generated Oct 12, 2013 4:02:28 PM by Hibernate Tools 3.4.0.CR1

/**
 * VolunteerInterest generated by hbm2java
 */
public class VolunteerInterest implements java.io.Serializable {

	private Integer volunteerInterestId;
	private Interest interest;
	private Volunteer volunteer;
	private byte disinterest;

	public VolunteerInterest() {
	}

	public VolunteerInterest(Interest interest, Volunteer volunteer,
			byte disinterest) {
		this.interest = interest;
		this.volunteer = volunteer;
		this.disinterest = disinterest;
	}

	public Integer getVolunteerInterestId() {
		return this.volunteerInterestId;
	}

	public void setVolunteerInterestId(Integer volunteerInterestId) {
		this.volunteerInterestId = volunteerInterestId;
	}

	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public byte getDisinterest() {
		return this.disinterest;
	}

	public void setDisinterest(byte disinterest) {
		this.disinterest = disinterest;
	}

}
