package org.CommunityService.EntitesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * GoogleLogIn generated by hbm2java
 */
public class GoogleLogIn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2749918530314605015L;
	private Integer googleLogInId;
	private Volunteer volunteer;
	private String token;

	public GoogleLogIn() {
	}

	public GoogleLogIn(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public GoogleLogIn(Volunteer volunteer, String token) {
		this.volunteer = volunteer;
		this.token = token;
	}

	public Integer getGoogleLogInId() {
		return this.googleLogInId;
	}

	public void setGoogleLogInId(Integer googleLogInId) {
		this.googleLogInId = googleLogInId;
	}

	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
