package org.CommunityService.EntitesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * OccurrencePattern generated by hbm2java
 */
public class OccurrencePattern implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7696629325960301314L;
	private Integer occurrencePatternId;
	private String ocurName;
	private String pattern;
	private Set<Event> events = new HashSet<Event>(0);

	public OccurrencePattern() {
	}

	public OccurrencePattern(String ocurName, String pattern) {
		this.ocurName = ocurName;
		this.pattern = pattern;
	}

	public OccurrencePattern(String ocurName, String pattern, Set<Event> events) {
		this.ocurName = ocurName;
		this.pattern = pattern;
		this.events = events;
	}

	public Integer getOccurrencePatternId() {
		return this.occurrencePatternId;
	}

	public void setOccurrencePatternId(Integer occurrencePatternId) {
		this.occurrencePatternId = occurrencePatternId;
	}

	public String getOcurName() {
		return this.ocurName;
	}

	public void setOcurName(String ocurName) {
		this.ocurName = ocurName;
	}

	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
