package org.CommunityService.EntitesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Picture generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2865739622916105671L;
	private Integer pictureId;
	private String pictureLink;
	private Date uploadedOn;
	private String albumName;
	private String description;
	private Set<Group> groups = new HashSet<Group>(0);
	private Set<Volunteer> volunteers = new HashSet<Volunteer>(0);
	private Set<Organization> organizations = new HashSet<Organization>(0);
	private Set<Event> events = new HashSet<Event>(0);

	public Picture() {
	}

	public Picture(String pictureLink) {
		this.pictureLink = pictureLink;
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName, String description, Set<Group> groups, Set<Volunteer> volunteers,
			Set<Organization> organizations, Set<Event> events) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
		this.description = description;
		this.groups = groups;
		this.volunteers = volunteers;
		this.organizations = organizations;
		this.events = events;
	}

	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	public String getPictureLink() {
		return this.pictureLink;
	}

	public void setPictureLink(String pictureLink) {
		this.pictureLink = pictureLink;
	}

	public Date getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(Date uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	public Set<Volunteer> getVolunteers() {
		return this.volunteers;
	}

	public void setVolunteers(Set<Volunteer> volunteers) {
		this.volunteers = volunteers;
	}

	public Set<Organization> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
