package Test;

// Generated Feb 3, 2014 2:14:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventSkillId generated by hbm2java
 */
@Embeddable
public class EventSkillId implements java.io.Serializable {

	private int skillId;
	private int eventId;

	public EventSkillId() {
	}

	public EventSkillId(int skillId, int eventId) {
		this.skillId = skillId;
		this.eventId = eventId;
	}

	@Column(name = "SkillID", nullable = false)
	public int getSkillId() {
		return this.skillId;
	}

	public void setSkillId(int skillId) {
		this.skillId = skillId;
	}

	@Column(name = "EventID", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventSkillId))
			return false;
		EventSkillId castOther = (EventSkillId) other;

		return (this.getSkillId() == castOther.getSkillId())
				&& (this.getEventId() == castOther.getEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSkillId();
		result = 37 * result + this.getEventId();
		return result;
	}

}
