package Test;

// Generated Feb 3, 2014 2:14:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupMod generated by hbm2java
 */
@Entity
@Table(name = "Group_Mod", catalog = "dbAppData")
public class GroupMod implements java.io.Serializable {

	private GroupModId id;
	private Group group;
	private Volunteer volunteer;
	private Date modSince;

	public GroupMod() {
	}

	public GroupMod(GroupModId id, Group group, Volunteer volunteer,
			Date modSince) {
		this.id = id;
		this.group = group;
		this.volunteer = volunteer;
		this.modSince = modSince;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "volunteerId", column = @Column(name = "VolunteerID", nullable = false)) })
	public GroupModId getId() {
		return this.id;
	}

	public void setId(GroupModId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID", nullable = false, insertable = false, updatable = false)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false, insertable = false, updatable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModSince", nullable = false, length = 19)
	public Date getModSince() {
		return this.modSince;
	}

	public void setModSince(Date modSince) {
		this.modSince = modSince;
	}

}
