package org.CommunityService.EntitiesMapped;

// Generated Feb 10, 2014 10:56:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventSkill generated by hbm2java
 */
@Entity
@Table(name = "Event_Skill", catalog = "dbAppData")
public class EventSkill implements java.io.Serializable {

	private EventSkillId id;
	private Event event;
	private Skill skill;
	private byte required;

	public EventSkill() {
	}

	public EventSkill(EventSkillId id, Event event, Skill skill, byte required) {
		this.id = id;
		this.event = event;
		this.skill = skill;
		this.required = required;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "skillId", column = @Column(name = "SkillID", nullable = false)),
			@AttributeOverride(name = "eventId", column = @Column(name = "EventID", nullable = false)) })
	public EventSkillId getId() {
		return this.id;
	}

	public void setId(EventSkillId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EventID", nullable = false, insertable = false, updatable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SkillID", nullable = false, insertable = false, updatable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@Column(name = "Required", nullable = false)
	public byte getRequired() {
		return this.required;
	}

	public void setRequired(byte required) {
		this.required = required;
	}

}
