package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "Event", catalog = "dbAppData")
public class Event implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -9157318856424457180L;
    private Integer eventId;
    private OccurrencePattern occurrencePattern;
    private String eventName;
    private String description;
    private String location;
    private Date beginTime;
    private Date endTime;
    private float hoursBonus;
    private Set<PictureEvent> pictureEvents = new HashSet<PictureEvent>(0);
    private Set<EventInterests> eventInterests = new HashSet<EventInterests>(0);
    private Set<EventSkill> eventSkills = new HashSet<EventSkill>(0);
    private Set<EventVolunteer> eventVolunteers = new HashSet<EventVolunteer>(0);

    public Event() {
    }

    public Event(String eventName, Date beginTime, Date endTime, float hoursBonus) {
	this.eventName = eventName;
	this.beginTime = beginTime;
	this.endTime = endTime;
	this.hoursBonus = hoursBonus;
    }

    public Event(OccurrencePattern occurrencePattern, String eventName, String description, String location, Date beginTime, Date endTime,
	    float hoursBonus, Set<PictureEvent> pictureEvents, Set<EventInterests> eventInterestses, Set<EventSkill> eventSkills, Set<EventVolunteer> eventVolunteers) {
	this.occurrencePattern = occurrencePattern;
	this.eventName = eventName;
	this.description = description;
	this.location = location;
	this.beginTime = beginTime;
	this.endTime = endTime;
	this.hoursBonus = hoursBonus;
	this.pictureEvents = pictureEvents;
	this.eventInterests = eventInterestses;
	this.eventSkills = eventSkills;
	this.eventVolunteers = eventVolunteers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EventID", unique = true, nullable = false)
    public Integer getEventId() {
	return this.eventId;
    }

    public void setEventId(Integer eventId) {
	this.eventId = eventId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RecurID")
    public OccurrencePattern getOccurrencePattern() {
	return this.occurrencePattern;
    }

    public void setOccurrencePattern(OccurrencePattern occurrencePattern) {
	this.occurrencePattern = occurrencePattern;
    }

    @Column(name = "EventName", nullable = false, length = 45)
    public String getEventName() {
	return this.eventName;
    }

    public void setEventName(String eventName) {
	this.eventName = eventName;
    }

    @Column(name = "Description")
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Column(name = "Location", length = 45)
    public String getLocation() {
	return this.location;
    }

    public void setLocation(String location) {
	this.location = location;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "BeginTime", nullable = false, length = 19)
    public Date getBeginTime() {
	return this.beginTime;
    }

    public void setBeginTime(Date beginTime) {
	this.beginTime = beginTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EndTime", nullable = false, length = 19)
    public Date getEndTime() {
	return this.endTime;
    }

    public void setEndTime(Date endTime) {
	this.endTime = endTime;
    }

    @Column(name = "HoursBonus", nullable = false, precision = 12, scale = 0)
    public float getHoursBonus() {
	return this.hoursBonus;
    }

    public void setHoursBonus(float hoursBonus) {
	this.hoursBonus = hoursBonus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set<PictureEvent> getPictureEvents() {
	return this.pictureEvents;
    }

    public void setPictureEvents(Set<PictureEvent> pictureEvents) {
	this.pictureEvents = pictureEvents;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set<EventInterests> getEventInterests() {
	return this.eventInterests;
    }

    public void setEventInterests(Set<EventInterests> eventInterestses) {
	this.eventInterests = eventInterestses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set<EventSkill> getEventSkills() {
	return this.eventSkills;
    }

    public void setEventSkills(Set<EventSkill> eventSkills) {
	this.eventSkills = eventSkills;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set<EventVolunteer> getEventVolunteers() {
	return this.eventVolunteers;
    }

    public void setEventVolunteers(Set<EventVolunteer> eventVolunteers) {
	this.eventVolunteers = eventVolunteers;
    }

}
