package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * EventVolunteer generated by hbm2java
 */
@Entity
@Table(name = "Event_Volunteer", catalog = "volunteerMeData")
public class EventVolunteer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1205262019793429482L;
	private Integer eventVolunteerId;
	private Event event;
	private Volunteer volunteer;
	private Integer attendedHours;
	private Boolean approved;

	public EventVolunteer() {
	}

	public EventVolunteer(Event event, Volunteer volunteer) {
		this.event = event;
		this.volunteer = volunteer;
	}

	public EventVolunteer(Event event, Volunteer volunteer, Integer attendedHours, Boolean approved) {
		this.event = event;
		this.volunteer = volunteer;
		this.attendedHours = attendedHours;
		this.approved = approved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EventVolunteerID", unique = true, nullable = false)
	public Integer getEventVolunteerId() {
		return this.eventVolunteerId;
	}

	public void setEventVolunteerId(Integer eventVolunteerId) {
		this.eventVolunteerId = eventVolunteerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EventID", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@Cascade({ CascadeType.SAVE_UPDATE })
	@JoinColumn(name = "VolunteerID", nullable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "AttendedHours")
	public Integer getAttendedHours() {
		return this.attendedHours;
	}

	public void setAttendedHours(Integer attendedHours) {
		this.attendedHours = attendedHours;
	}

	@Column(name = "Approved")
	public Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(Boolean approved) {
		this.approved = approved;
	}

}
