package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventSkill generated by hbm2java
 */
@Entity
@Table(name = "Event_Skill", catalog = "volunteerMeData")
public class EventSkill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5565384186697261955L;
	private Integer eventSkillId;
	private Event event;
	private Skill skill;
	private Boolean required;

	public EventSkill() {
	}

	public EventSkill(Event event, Skill skill) {
		this.event = event;
		this.skill = skill;
	}

	public EventSkill(Event event, Skill skill, Boolean required) {
		this.event = event;
		this.skill = skill;
		this.required = required;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EventSkillID", unique = true, nullable = false)
	public Integer getEventSkillId() {
		return this.eventSkillId;
	}

	public void setEventSkillId(Integer eventSkillId) {
		this.eventSkillId = eventSkillId;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "EventID", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "SkillID", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@Column(name = "Required")
	public Boolean getRequired() {
		return this.required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

}
