package org.CommunityService.EntitiesMapped;

// Generated Feb 10, 2014 11:13:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventVolunteerId generated by hbm2java
 */
@Embeddable
public class EventVolunteerId implements java.io.Serializable {

	private int eventId;
	private int volunteerD;

	public EventVolunteerId() {
	}

	public EventVolunteerId(int eventId, int volunteerD) {
		this.eventId = eventId;
		this.volunteerD = volunteerD;
	}

	@Column(name = "EventID", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "VolunteerD", nullable = false)
	public int getVolunteerD() {
		return this.volunteerD;
	}

	public void setVolunteerD(int volunteerD) {
		this.volunteerD = volunteerD;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventVolunteerId))
			return false;
		EventVolunteerId castOther = (EventVolunteerId) other;

		return (this.getEventId() == castOther.getEventId()) && (this.getVolunteerD() == castOther.getVolunteerD());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventId();
		result = 37 * result + this.getVolunteerD();
		return result;
	}

}
