package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventSkill generated by hbm2java
 */
@Entity
@Table(name = "EventSkill", catalog = "dbAppData")
public class EventSkill implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4436535099145973162L;
    private Integer eventSkillId;
    private Event event;
    private Skill skill;
    private byte required;

    public EventSkill() {
    }

    public EventSkill(Event event, Skill skill, byte required) {
	this.event = event;
	this.skill = skill;
	this.required = required;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EventSkillID", unique = true, nullable = false)
    public Integer getEventSkillId() {
	return this.eventSkillId;
    }

    public void setEventSkillId(Integer eventSkillId) {
	this.eventSkillId = eventSkillId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EventID", nullable = false)
    public Event getEvent() {
	return this.event;
    }

    public void setEvent(Event event) {
	this.event = event;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SkillID", nullable = false)
    public Skill getSkill() {
	return this.skill;
    }

    public void setSkill(Skill skill) {
	this.skill = skill;
    }

    @Column(name = "Required", nullable = false)
    public byte getRequired() {
	return this.required;
    }

    public void setRequired(byte required) {
	this.required = required;
    }

}
