package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventVolunteer generated by hbm2java
 */
@Entity
@Table(name = "EventVolunteer", catalog = "dbAppData")
public class EventVolunteer implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 982901817810509299L;
    private int eventVolunteerId;
    private Event event;
    private Volunteer volunteer;
    private int attendedHours;

    public EventVolunteer() {
    }

    public EventVolunteer(int eventVolunteerId, Event event, Volunteer volunteer, int attendedHours) {
	this.eventVolunteerId = eventVolunteerId;
	this.event = event;
	this.volunteer = volunteer;
	this.attendedHours = attendedHours;
    }

    @Id
    @Column(name = "EventVolunteerID", unique = true, nullable = false)
    public int getEventVolunteerId() {
	return this.eventVolunteerId;
    }

    public void setEventVolunteerId(int eventVolunteerId) {
	this.eventVolunteerId = eventVolunteerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EventID", nullable = false)
    public Event getEvent() {
	return this.event;
    }

    public void setEvent(Event event) {
	this.event = event;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerD", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

    @Column(name = "AttendedHours", nullable = false)
    public int getAttendedHours() {
	return this.attendedHours;
    }

    public void setAttendedHours(int attendedHours) {
	this.attendedHours = attendedHours;
    }

}
