package org.CommunityService.EntitiesMapped;

// Generated Feb 3, 2014 2:50:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FacebookLogIn generated by hbm2java
 */
@Entity
@Table(name = "FacebookLogIn", catalog = "dbAppData", uniqueConstraints = @UniqueConstraint(columnNames = "FacebookLogInID"))
public class FacebookLogIn implements java.io.Serializable {

	private FacebookLogInId id;
	private Volunteer volunteer;
	private String token;

	public FacebookLogIn() {
	}

	public FacebookLogIn(FacebookLogInId id, Volunteer volunteer, String token) {
		this.id = id;
		this.volunteer = volunteer;
		this.token = token;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "facebookLogInId", column = @Column(name = "FacebookLogInID", unique = true, nullable = false)),
			@AttributeOverride(name = "volunteerId", column = @Column(name = "VolunteerID", nullable = false)) })
	public FacebookLogInId getId() {
		return this.id;
	}

	public void setId(FacebookLogInId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false, insertable = false, updatable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "Token", nullable = false, length = 45)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
