package org.CommunityService.EntitiesMapped;

// Generated Feb 10, 2014 10:56:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacebookLogInId generated by hbm2java
 */
@Embeddable
public class FacebookLogInId implements java.io.Serializable {

	private int facebookLogInId;
	private int volunteerId;

	public FacebookLogInId() {
	}

	public FacebookLogInId(int facebookLogInId, int volunteerId) {
		this.facebookLogInId = facebookLogInId;
		this.volunteerId = volunteerId;
	}

	@Column(name = "FacebookLogInID", unique = true, nullable = false)
	public int getFacebookLogInId() {
		return this.facebookLogInId;
	}

	public void setFacebookLogInId(int facebookLogInId) {
		this.facebookLogInId = facebookLogInId;
	}

	@Column(name = "VolunteerID", nullable = false)
	public int getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacebookLogInId))
			return false;
		FacebookLogInId castOther = (FacebookLogInId) other;

		return (this.getFacebookLogInId() == castOther.getFacebookLogInId())
				&& (this.getVolunteerId() == castOther.getVolunteerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFacebookLogInId();
		result = 37 * result + this.getVolunteerId();
		return result;
	}

}
