package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupMod generated by hbm2java
 */
@Entity
@Table(name = "GroupMod", catalog = "dbAppData")
public class GroupMod implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -1371146483555657623L;
    private Integer groupModId;
    private Group group;
    private Volunteer volunteer;
    private Date modSince;

    public GroupMod() {
    }

    public GroupMod(Group group, Volunteer volunteer, Date modSince) {
	this.group = group;
	this.volunteer = volunteer;
	this.modSince = modSince;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "GroupModID", unique = true, nullable = false)
    public Integer getGroupModId() {
	return this.groupModId;
    }

    public void setGroupModId(Integer groupModId) {
	this.groupModId = groupModId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GroupID", nullable = false)
    public Group getGroup() {
	return this.group;
    }

    public void setGroup(Group group) {
	this.group = group;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ModSince", nullable = false, length = 19)
    public Date getModSince() {
	return this.modSince;
    }

    public void setModSince(Date modSince) {
	this.modSince = modSince;
    }

}
