package org.CommunityService.EntitiesMapped;

// Generated Feb 3, 2014 2:14:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupMember generated by hbm2java
 */
@Entity
@Table(name = "Group_Member", catalog = "dbAppData")
public class GroupMember implements java.io.Serializable {

	private GroupMemberId id;
	private Group group;
	private Volunteer volunteer;
	private Date joinedDate;

	public GroupMember() {
	}

	public GroupMember(GroupMemberId id, Group group, Volunteer volunteer,
			Date joinedDate) {
		this.id = id;
		this.group = group;
		this.volunteer = volunteer;
		this.joinedDate = joinedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "volunteerId", column = @Column(name = "VolunteerID", nullable = false)) })
	public GroupMemberId getId() {
		return this.id;
	}

	public void setId(GroupMemberId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID", nullable = false, insertable = false, updatable = false)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false, insertable = false, updatable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JoinedDate", nullable = false, length = 19)
	public Date getJoinedDate() {
		return this.joinedDate;
	}

	public void setJoinedDate(Date joinedDate) {
		this.joinedDate = joinedDate;
	}

}
