package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupMember generated by hbm2java
 */
@Entity
@Table(name = "Group_Member", catalog = "volunteerMeData")
public class GroupMember implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3493373322854337264L;
	private Integer groupMemberId;
	private Group group;
	private Volunteer volunteer;
	private Date joinedDate;
	private Boolean mod;
	private Boolean admin;

	public GroupMember() {
	}

	public GroupMember(Group group, Volunteer volunteer) {
		this.group = group;
		this.volunteer = volunteer;
	}

	public GroupMember(Group group, Volunteer volunteer, Date joinedDate, Boolean mod, Boolean admin) {
		this.group = group;
		this.volunteer = volunteer;
		this.joinedDate = joinedDate;
		this.mod = mod;
		this.admin = admin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GroupMemberID", unique = true, nullable = false)
	public Integer getGroupMemberId() {
		return this.groupMemberId;
	}

	public void setGroupMemberId(Integer groupMemberId) {
		this.groupMemberId = groupMemberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID", nullable = false)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JoinedDate", length = 19)
	public Date getJoinedDate() {
		return this.joinedDate;
	}

	public void setJoinedDate(Date joinedDate) {
		this.joinedDate = joinedDate;
	}

	@Column(name = "Moderator")
	public Boolean getMod() {
		return this.mod;
	}

	public void setMod(Boolean mod) {
		this.mod = mod;
	}

	@Column(name = "Admin")
	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

}
