package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "Notification", catalog = "volunteerMeData")
public class Notification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3992575582339276397L;
	private Integer notificationId;
	private String description;
	private String category;
	private String key;
	private String value;
	private Date creation;
	private Date dependenceDate;
	private Set<Volunteer> volunteers = new HashSet<Volunteer>(0);

	public Notification() {
	}

	public Notification(String description) {
		this.description = description;
	}

	public Notification(String description, String category, String key, String value, Date creation, Date dependenceDate, Set<Volunteer> volunteers) {
		this.description = description;
		this.category = category;
		this.key = key;
		this.value = value;
		this.creation = creation;
		this.dependenceDate = dependenceDate;
		this.volunteers = volunteers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NotificationID", unique = true, nullable = false)
	public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "Key", length = 45)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "Value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation", length = 19)
	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DependenceDate", length = 19)
	public Date getDependenceDate() {
		return this.dependenceDate;
	}

	public void setDependenceDate(Date dependenceDate) {
		this.dependenceDate = dependenceDate;
	}

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "Notification_Volunteer", catalog = "volunteerMeData", joinColumns = { @JoinColumn(name = "NotificationID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "VolunteerID", nullable = false, updatable = false) })
	public Set<Volunteer> getVolunteers() {
		return this.volunteers;
	}

	public void setVolunteers(Set<Volunteer> volunteers) {
		this.volunteers = volunteers;
	}

}
