package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 9:09:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OccurrencePattern generated by hbm2java
 */
@Entity
@Table(name = "OccurrencePattern", catalog = "volunteerMeData")
public class OccurrencePattern implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9066073474025449947L;
	private Integer occurrencePatternId;
	private String ocurName;
	private String pattern;
	private Set<Event> events = new HashSet<Event>(0);

	public OccurrencePattern() {
	}

	public OccurrencePattern(String ocurName, String pattern) {
		this.ocurName = ocurName;
		this.pattern = pattern;
	}

	public OccurrencePattern(String ocurName, String pattern, Set<Event> events) {
		this.ocurName = ocurName;
		this.pattern = pattern;
		this.events = events;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OccurrencePatternID", unique = true, nullable = false)
	public Integer getOccurrencePatternId() {
		return this.occurrencePatternId;
	}

	public void setOccurrencePatternId(Integer occurrencePatternId) {
		this.occurrencePatternId = occurrencePatternId;
	}

	@Column(name = "OcurName", nullable = false, length = 20)
	public String getOcurName() {
		return this.ocurName;
	}

	public void setOcurName(String ocurName) {
		this.ocurName = ocurName;
	}

	@Column(name = "Pattern", nullable = false, length = 45)
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "occurrencePattern", cascade = CascadeType.ALL)
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
