package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrganizationFollower generated by hbm2java
 */
@Entity
@Table(name = "Organization_Follower", catalog = "volunteerMeData")
public class OrganizationFollower implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9148778755891001557L;
	private Integer orgFollowerId;
	private Organization organization;
	private Volunteer volunteer;
	private Boolean mod;
	private Boolean admin;

	public OrganizationFollower() {
	}

	public OrganizationFollower(Organization organization, Volunteer volunteer) {
		this.organization = organization;
		this.volunteer = volunteer;
	}

	public OrganizationFollower(Organization organization, Volunteer volunteer, Boolean mod, Boolean admin) {
		this.organization = organization;
		this.volunteer = volunteer;
		this.mod = mod;
		this.admin = admin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OrgFollowerID", unique = true, nullable = false)
	public Integer getOrgFollowerId() {
		return this.orgFollowerId;
	}

	public void setOrgFollowerId(Integer orgFollowerId) {
		this.orgFollowerId = orgFollowerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrgID", nullable = false)
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "Moderator")
	public Boolean getMod() {
		return this.mod;
	}

	public void setMod(Boolean mod) {
		this.mod = mod;
	}

	@Column(name = "Admin")
	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

}
