package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrgFollower generated by hbm2java
 */
@Entity
@Table(name = "OrgFollower", catalog = "dbAppData")
public class OrgFollower implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -3690818850910802455L;
    private Integer orgFollowerId;
    private Organization organization;
    private Volunteer volunteer;

    public OrgFollower() {
    }

    public OrgFollower(Organization organization, Volunteer volunteer) {
	this.organization = organization;
	this.volunteer = volunteer;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "OrgFollowerID", unique = true, nullable = false)
    public Integer getOrgFollowerId() {
	return this.orgFollowerId;
    }

    public void setOrgFollowerId(Integer orgFollowerId) {
	this.orgFollowerId = orgFollowerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrgID", nullable = false)
    public Organization getOrganization() {
	return this.organization;
    }

    public void setOrganization(Organization organization) {
	this.organization = organization;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

}
