package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrgGroup generated by hbm2java
 */
@Entity
@Table(name = "OrgGroup", catalog = "dbAppData")
public class OrgGroup implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 28464276073612014L;
    private int orgGroupId;
    private Organization organization;
    private Group group;

    public OrgGroup() {
    }

    public OrgGroup(int orgGroupId, Organization organization, Group group) {
	this.orgGroupId = orgGroupId;
	this.organization = organization;
	this.group = group;
    }

    @Id
    @Column(name = "OrgGroupID", unique = true, nullable = false)
    public int getOrgGroupId() {
	return this.orgGroupId;
    }

    public void setOrgGroupId(int orgGroupId) {
	this.orgGroupId = orgGroupId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrgID", nullable = false)
    public Organization getOrganization() {
	return this.organization;
    }

    public void setOrganization(Organization organization) {
	this.organization = organization;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GroupID", nullable = false)
    public Group getGroup() {
	return this.group;
    }

    public void setGroup(Group group) {
	this.group = group;
    }

}
