package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrgMod generated by hbm2java
 */
@Entity
@Table(name = "OrgMod", catalog = "dbAppData")
public class OrgMod implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 2377144436223926238L;
    private int orgModId;
    private Organization organization;
    private Volunteer volunteer;

    public OrgMod() {
    }

    public OrgMod(int orgModId, Organization organization, Volunteer volunteer) {
	this.orgModId = orgModId;
	this.organization = organization;
	this.volunteer = volunteer;
    }

    @Id
    @Column(name = "OrgModID", unique = true, nullable = false)
    public int getOrgModId() {
	return this.orgModId;
    }

    public void setOrgModId(int orgModId) {
	this.orgModId = orgModId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrgID", nullable = false)
    public Organization getOrganization() {
	return this.organization;
    }

    public void setOrganization(Organization organization) {
	this.organization = organization;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

}
