package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PictureGroup generated by hbm2java
 */
@Entity
@Table(name = "PictureGroup", catalog = "dbAppData")
public class PictureGroup implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4701285402071745194L;
    private Integer pictureGroupId;
    private Group group;
    private Picture picture;

    public PictureGroup() {
    }

    public PictureGroup(Group group, Picture picture) {
	this.group = group;
	this.picture = picture;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "PictureGroupID", unique = true, nullable = false)
    public Integer getPictureGroupId() {
	return this.pictureGroupId;
    }

    public void setPictureGroupId(Integer pictureGroupId) {
	this.pictureGroupId = pictureGroupId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GroupID", nullable = false)
    public Group getGroup() {
	return this.group;
    }

    public void setGroup(Group group) {
	this.group = group;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PictureID", nullable = false)
    public Picture getPicture() {
	return this.picture;
    }

    public void setPicture(Picture picture) {
	this.picture = picture;
    }

}
