package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PictureVolunteer generated by hbm2java
 */
@Entity
@Table(name = "PictureVolunteer", catalog = "dbAppData")
public class PictureVolunteer implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7618690634433763703L;
    private int pictureVolunteerId;
    private Volunteer volunteer;
    private Picture picture;

    public PictureVolunteer() {
    }

    public PictureVolunteer(int pictureVolunteerId, Volunteer volunteer, Picture picture) {
	this.pictureVolunteerId = pictureVolunteerId;
	this.volunteer = volunteer;
	this.picture = picture;
    }

    @Id
    @Column(name = "PictureVolunteerID", unique = true, nullable = false)
    public int getPictureVolunteerId() {
	return this.pictureVolunteerId;
    }

    public void setPictureVolunteerId(int pictureVolunteerId) {
	this.pictureVolunteerId = pictureVolunteerId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PictureID", nullable = false)
    public Picture getPicture() {
	return this.picture;
    }

    public void setPicture(Picture picture) {
	this.picture = picture;
    }

}
