package org.CommunityService.EntitiesMapped;

// Generated Feb 10, 2014 11:13:03 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PictureEvent generated by hbm2java
 */
@Entity
@Table(name = "Picture_Event", catalog = "dbAppData")
public class PictureEvent implements java.io.Serializable {

	private PictureEventId id;

	public PictureEvent() {
	}

	public PictureEvent(PictureEventId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pictureId", column = @Column(name = "PictureID", nullable = false)),
			@AttributeOverride(name = "eventId", column = @Column(name = "EventID", nullable = false)) })
	public PictureEventId getId() {
		return this.id;
	}

	public void setId(PictureEventId id) {
		this.id = id;
	}

}
