package org.CommunityService.EntitiesMapped;

// Generated Feb 3, 2014 2:14:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Picture generated by hbm2java
 */
@Entity
@Table(name = "Picture", catalog = "dbAppData", uniqueConstraints = @UniqueConstraint(columnNames = "PictureLink"))
public class Picture implements java.io.Serializable {

	private Integer pictureId;
	private String pictureLink;
	private Date uploadedOn;
	private String albumName;
	private String description;
	private Set groups = new HashSet(0);
	private Set volunteers = new HashSet(0);
	private Set organizations = new HashSet(0);

	public Picture() {
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
	}

	public Picture(String pictureLink, Date uploadedOn, String albumName,
			String description, Set groups, Set volunteers, Set organizations) {
		this.pictureLink = pictureLink;
		this.uploadedOn = uploadedOn;
		this.albumName = albumName;
		this.description = description;
		this.groups = groups;
		this.volunteers = volunteers;
		this.organizations = organizations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PictureID", unique = true, nullable = false)
	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	@Column(name = "PictureLink", unique = true, nullable = false, length = 45)
	public String getPictureLink() {
		return this.pictureLink;
	}

	public void setPictureLink(String pictureLink) {
		this.pictureLink = pictureLink;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UploadedOn", nullable = false, length = 19)
	public Date getUploadedOn() {
		return this.uploadedOn;
	}

	public void setUploadedOn(Date uploadedOn) {
		this.uploadedOn = uploadedOn;
	}

	@Column(name = "AlbumName", nullable = false, length = 45)
	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	@Column(name = "Description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Picture_Group", catalog = "dbAppData", joinColumns = { @JoinColumn(name = "PictureID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "GroupID", nullable = false, updatable = false) })
	public Set getGroups() {
		return this.groups;
	}

	public void setGroups(Set groups) {
		this.groups = groups;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Picture_Volunteer", catalog = "dbAppData", joinColumns = { @JoinColumn(name = "PictureID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "VolunteerID", nullable = false, updatable = false) })
	public Set getVolunteers() {
		return this.volunteers;
	}

	public void setVolunteers(Set volunteers) {
		this.volunteers = volunteers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Picture_Organization", catalog = "dbAppData", joinColumns = { @JoinColumn(name = "PictureID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "OrgID", nullable = false, updatable = false) })
	public Set getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set organizations) {
		this.organizations = organizations;
	}

}
