package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PictureOrg generated by hbm2java
 */
@Entity
@Table(name = "PictureOrg", catalog = "dbAppData")
public class PictureOrg implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6675249127083620867L;
    private int pictureOrgId;
    private Organization organization;
    private Picture picture;

    public PictureOrg() {
    }

    public PictureOrg(int pictureOrgId, Organization organization, Picture picture) {
	this.pictureOrgId = pictureOrgId;
	this.organization = organization;
	this.picture = picture;
    }

    @Id
    @Column(name = "PictureOrgID", unique = true, nullable = false)
    public int getPictureOrgId() {
	return this.pictureOrgId;
    }

    public void setPictureOrgId(int pictureOrgId) {
	this.pictureOrgId = pictureOrgId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrgID", nullable = false)
    public Organization getOrganization() {
	return this.organization;
    }

    public void setOrganization(Organization organization) {
	this.organization = organization;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PictureID", nullable = false)
    public Picture getPicture() {
	return this.picture;
    }

    public void setPicture(Picture picture) {
	this.picture = picture;
    }

}
