package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VolunteerDevice generated by hbm2java
 */
@Entity
@Table(name = "Volunteer_Device", catalog = "volunteerMeData", uniqueConstraints = @UniqueConstraint(columnNames = "DeviceTokenInternal"))
public class VolunteerDevice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5872486019154410285L;
	private Integer deviceId;
	private Volunteer volunteer;
	private String deviceTokenInternal;

	public VolunteerDevice() {
	}

	public VolunteerDevice(Volunteer volunteer, String deviceTokenInternal) {
		this.volunteer = volunteer;
		this.deviceTokenInternal = deviceTokenInternal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DeviceID", unique = true, nullable = false)
	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "DeviceTokenInternal", unique = true, nullable = false, length = 45)
	public String getDeviceTokenInternal() {
		return this.deviceTokenInternal;
	}

	public void setDeviceTokenInternal(String deviceTokenInternal) {
		this.deviceTokenInternal = deviceTokenInternal;
	}

}
