package org.CommunityService.EntitiesMapped;

// Generated Feb 3, 2014 2:50:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VolunteerInterestId generated by hbm2java
 */
@Embeddable
public class VolunteerInterestId implements java.io.Serializable {

	private int interestId;
	private int volunteerId;

	public VolunteerInterestId() {
	}

	public VolunteerInterestId(int interestId, int volunteerId) {
		this.interestId = interestId;
		this.volunteerId = volunteerId;
	}

	@Column(name = "InterestID", nullable = false)
	public int getInterestId() {
		return this.interestId;
	}

	public void setInterestId(int interestId) {
		this.interestId = interestId;
	}

	@Column(name = "VolunteerID", nullable = false)
	public int getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VolunteerInterestId))
			return false;
		VolunteerInterestId castOther = (VolunteerInterestId) other;

		return (this.getInterestId() == castOther.getInterestId())
				&& (this.getVolunteerId() == castOther.getVolunteerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInterestId();
		result = 37 * result + this.getVolunteerId();
		return result;
	}

}
