package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VolunteerSkill generated by hbm2java
 */
@Entity
@Table(name = "VolunteerSkill", catalog = "dbAppData")
public class VolunteerSkill implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -1888246113077992431L;
    private Integer volunteerSkillId;
    private Skill skill;
    private Volunteer volunteer;
    private byte certified;
    private String certifiedFrom;

    public VolunteerSkill() {
    }

    public VolunteerSkill(Skill skill, Volunteer volunteer, byte certified) {
	this.skill = skill;
	this.volunteer = volunteer;
	this.certified = certified;
    }

    public VolunteerSkill(Skill skill, Volunteer volunteer, byte certified, String certifiedFrom) {
	this.skill = skill;
	this.volunteer = volunteer;
	this.certified = certified;
	this.certifiedFrom = certifiedFrom;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "VolunteerSkillID", unique = true, nullable = false)
    public Integer getVolunteerSkillId() {
	return this.volunteerSkillId;
    }

    public void setVolunteerSkillId(Integer volunteerSkillId) {
	this.volunteerSkillId = volunteerSkillId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SkillID", nullable = false)
    public Skill getSkill() {
	return this.skill;
    }

    public void setSkill(Skill skill) {
	this.skill = skill;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

    @Column(name = "Certified", nullable = false)
    public byte getCertified() {
	return this.certified;
    }

    public void setCertified(byte certified) {
	this.certified = certified;
    }

    @Column(name = "CertifiedFrom", length = 45)
    public String getCertifiedFrom() {
	return this.certifiedFrom;
    }

    public void setCertifiedFrom(String certifiedFrom) {
	this.certifiedFrom = certifiedFrom;
    }

}
