package org.CommunityService.EntitiesMapped;

// Generated Feb 3, 2014 2:50:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VolunteerDevice generated by hbm2java
 */
@Entity
@Table(name = "Volunteer_Device", catalog = "dbAppData", uniqueConstraints = {
		@UniqueConstraint(columnNames = "VolunteerID"),
		@UniqueConstraint(columnNames = "DeviceTokenInternal") })
public class VolunteerDevice implements java.io.Serializable {

	private VolunteerDeviceId id;
	private String deviceTokenInternal;

	public VolunteerDevice() {
	}

	public VolunteerDevice(VolunteerDeviceId id, String deviceTokenInternal) {
		this.id = id;
		this.deviceTokenInternal = deviceTokenInternal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "deviceId", column = @Column(name = "DeviceID", nullable = false, length = 45)),
			@AttributeOverride(name = "volunteerId", column = @Column(name = "VolunteerID", unique = true, nullable = false)) })
	public VolunteerDeviceId getId() {
		return this.id;
	}

	public void setId(VolunteerDeviceId id) {
		this.id = id;
	}

	@Column(name = "DeviceTokenInternal", unique = true, nullable = false, length = 45)
	public String getDeviceTokenInternal() {
		return this.deviceTokenInternal;
	}

	public void setDeviceTokenInternal(String deviceTokenInternal) {
		this.deviceTokenInternal = deviceTokenInternal;
	}

}
