package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VolunteerInterest generated by hbm2java
 */
@Entity
@Table(name = "Volunteer_Interest", catalog = "volunteerMeData")
public class VolunteerInterest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6604650043908909472L;
	private Integer volunteerInterestId;
	private Interest interest;
	private Volunteer volunteer;
	private Boolean disinterest;

	public VolunteerInterest() {
	}

	public VolunteerInterest(Interest interest, Volunteer volunteer) {
		this.interest = interest;
		this.volunteer = volunteer;
	}

	public VolunteerInterest(Interest interest, Volunteer volunteer, Boolean disinterest) {
		this.interest = interest;
		this.volunteer = volunteer;
		this.disinterest = disinterest;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VolunteerInterestID", unique = true, nullable = false)
	public Integer getVolunteerInterestId() {
		return this.volunteerInterestId;
	}

	public void setVolunteerInterestId(Integer volunteerInterestId) {
		this.volunteerInterestId = volunteerInterestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InterestID", nullable = false)
	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "Disinterest")
	public Boolean getDisinterest() {
		return this.disinterest;
	}

	public void setDisinterest(Boolean disinterest) {
		this.disinterest = disinterest;
	}

}
