package org.CommunityService.EntitiesMapped;

// Generated Feb 10, 2014 10:56:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VolunteerSkillId generated by hbm2java
 */
@Embeddable
public class VolunteerSkillId implements java.io.Serializable {

	private int skillId;
	private int volunteerId;

	public VolunteerSkillId() {
	}

	public VolunteerSkillId(int skillId, int volunteerId) {
		this.skillId = skillId;
		this.volunteerId = volunteerId;
	}

	@Column(name = "SkillID", nullable = false)
	public int getSkillId() {
		return this.skillId;
	}

	public void setSkillId(int skillId) {
		this.skillId = skillId;
	}

	@Column(name = "VolunteerID", nullable = false)
	public int getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VolunteerSkillId))
			return false;
		VolunteerSkillId castOther = (VolunteerSkillId) other;

		return (this.getSkillId() == castOther.getSkillId()) && (this.getVolunteerId() == castOther.getVolunteerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSkillId();
		result = 37 * result + this.getVolunteerId();
		return result;
	}

}
