package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VolunteerInterest generated by hbm2java
 */
@Entity
@Table(name = "VolunteerInterest", catalog = "dbAppData")
public class VolunteerInterest implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6431972097532274622L;
    private Integer volunteerInterestId;
    private Interest interest;
    private Volunteer volunteer;
    private byte disinterest;

    public VolunteerInterest() {
    }

    public VolunteerInterest(Interest interest, Volunteer volunteer, byte disinterest) {
	this.interest = interest;
	this.volunteer = volunteer;
	this.disinterest = disinterest;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "VolunteerInterestID", unique = true, nullable = false)
    public Integer getVolunteerInterestId() {
	return this.volunteerInterestId;
    }

    public void setVolunteerInterestId(Integer volunteerInterestId) {
	this.volunteerInterestId = volunteerInterestId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "InterestID", nullable = false)
    public Interest getInterest() {
	return this.interest;
    }

    public void setInterest(Interest interest) {
	this.interest = interest;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

    @Column(name = "Disinterest", nullable = false)
    public byte getDisinterest() {
	return this.disinterest;
    }

    public void setDisinterest(byte disinterest) {
	this.disinterest = disinterest;
    }

}
