package org.CommunityService.EntitiesMapped;

// Generated Feb 22, 2014 8:45:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VolunteerSkill generated by hbm2java
 */
@Entity
@Table(name = "Volunteer_Skill", catalog = "volunteerMeData")
public class VolunteerSkill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9157930356898140967L;
	private Integer volunteerSkillId;
	private Skill skill;
	private Volunteer volunteer;
	private Boolean certified;
	private String certifiedFrom;

	public VolunteerSkill() {
	}

	public VolunteerSkill(Skill skill, Volunteer volunteer) {
		this.skill = skill;
		this.volunteer = volunteer;
	}

	public VolunteerSkill(Skill skill, Volunteer volunteer, Boolean certified, String certifiedFrom) {
		this.skill = skill;
		this.volunteer = volunteer;
		this.certified = certified;
		this.certifiedFrom = certifiedFrom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VolunteerSkillID", unique = true, nullable = false)
	public Integer getVolunteerSkillId() {
		return this.volunteerSkillId;
	}

	public void setVolunteerSkillId(Integer volunteerSkillId) {
		this.volunteerSkillId = volunteerSkillId;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "SkillID", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "VolunteerID", nullable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "Certified")
	public Boolean getCertified() {
		return this.certified;
	}

	public void setCertified(Boolean certified) {
		this.certified = certified;
	}

	@Column(name = "CertifiedFrom", length = 45)
	public String getCertifiedFrom() {
		return this.certifiedFrom;
	}

	public void setCertifiedFrom(String certifiedFrom) {
		this.certifiedFrom = certifiedFrom;
	}

}
