package org.CommunityService.EntitiesMapped;

// Generated Oct 21, 2013 2:07:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VolunteerDevice generated by hbm2java
 */
@Entity
@Table(name = "VolunteerDevice", catalog = "dbAppData", uniqueConstraints = { @UniqueConstraint(columnNames = "VolunteerID"),
	@UniqueConstraint(columnNames = "DeviceTokenInternal") })
public class VolunteerDevice implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8721712793647994812L;
    private int volunteerDeviceId;
    private Volunteer volunteer;
    private String deviceId;
    private String deviceTokenInternal;

    public VolunteerDevice() {
    }

    public VolunteerDevice(int volunteerDeviceId, Volunteer volunteer, String deviceTokenInternal) {
	this.volunteerDeviceId = volunteerDeviceId;
	this.volunteer = volunteer;
	this.deviceTokenInternal = deviceTokenInternal;
    }

    public VolunteerDevice(int volunteerDeviceId, Volunteer volunteer, String deviceId, String deviceTokenInternal) {
	this.volunteerDeviceId = volunteerDeviceId;
	this.volunteer = volunteer;
	this.deviceId = deviceId;
	this.deviceTokenInternal = deviceTokenInternal;
    }

    @Id
    @Column(name = "VolunteerDeviceID", unique = true, nullable = false)
    public int getVolunteerDeviceId() {
	return this.volunteerDeviceId;
    }

    public void setVolunteerDeviceId(int volunteerDeviceId) {
	this.volunteerDeviceId = volunteerDeviceId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VolunteerID", unique = true, nullable = false)
    public Volunteer getVolunteer() {
	return this.volunteer;
    }

    public void setVolunteer(Volunteer volunteer) {
	this.volunteer = volunteer;
    }

    @Column(name = "DeviceID", length = 45)
    public String getDeviceId() {
	return this.deviceId;
    }

    public void setDeviceId(String deviceId) {
	this.deviceId = deviceId;
    }

    @Column(name = "DeviceTokenInternal", unique = true, nullable = false, length = 45)
    public String getDeviceTokenInternal() {
	return this.deviceTokenInternal;
    }

    public void setDeviceTokenInternal(String deviceTokenInternal) {
	this.deviceTokenInternal = deviceTokenInternal;
    }

}
