package org.CommunityService.EntitiesMapped;

// Generated Feb 3, 2014 2:14:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VolunteerInterest generated by hbm2java
 */
@Entity
@Table(name = "Volunteer_Interest", catalog = "dbAppData")
public class VolunteerInterest implements java.io.Serializable {

	private VolunteerInterestId id;
	private Interest interest;
	private Volunteer volunteer;
	private byte disinterest;

	public VolunteerInterest() {
	}

	public VolunteerInterest(VolunteerInterestId id, Interest interest,
			Volunteer volunteer, byte disinterest) {
		this.id = id;
		this.interest = interest;
		this.volunteer = volunteer;
		this.disinterest = disinterest;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "interestId", column = @Column(name = "InterestID", nullable = false)),
			@AttributeOverride(name = "volunteerId", column = @Column(name = "VolunteerID", nullable = false)) })
	public VolunteerInterestId getId() {
		return this.id;
	}

	public void setId(VolunteerInterestId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InterestID", nullable = false, insertable = false, updatable = false)
	public Interest getInterest() {
		return this.interest;
	}

	public void setInterest(Interest interest) {
		this.interest = interest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VolunteerID", nullable = false, insertable = false, updatable = false)
	public Volunteer getVolunteer() {
		return this.volunteer;
	}

	public void setVolunteer(Volunteer volunteer) {
		this.volunteer = volunteer;
	}

	@Column(name = "Disinterest", nullable = false)
	public byte getDisinterest() {
		return this.disinterest;
	}

	public void setDisinterest(byte disinterest) {
		this.disinterest = disinterest;
	}

}
