package org.CommunityService.EntitesUnmapped;

// Generated Feb 23, 2014 5:44:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Interest generated by hbm2java
 */
public class Interest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 189290710267380842L;
	private Integer interestId;
	private String name;
	private String description;
	private Set<VolunteerInterest> volunteerInterests = new HashSet<VolunteerInterest>(0);
	private Set<Event> events = new HashSet<Event>(0);

	public Interest() {
	}

	public Interest(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Interest(String name, String description, Set<VolunteerInterest> volunteerInterests, Set<Event> events) {
		this.name = name;
		this.description = description;
		this.volunteerInterests = volunteerInterests;
		this.events = events;
	}

	public Integer getInterestId() {
		return this.interestId;
	}

	public void setInterestId(Integer interestId) {
		this.interestId = interestId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<VolunteerInterest> getVolunteerInterests() {
		return this.volunteerInterests;
	}

	public void setVolunteerInterests(Set<VolunteerInterest> volunteerInterests) {
		this.volunteerInterests = volunteerInterests;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
